const numberButtons = document.querySelectorAll('[data-number]')
const numberButtons = document.querySelectorAll('[data-operation]')
const numberButtons = document.querySelector('[data-equals]')
const numberButtons = document.querySelector('[data-delete]')
const numberButtons = document.querySelector('[data-all-clear]')
